# This is a basic workflow to help you get started with Actions

name: Create_TestFiles

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        name: Checkout repository

      # Create the test files
      - name: Run a multi-line script
        run: |
          bash ErrLog.sh -P tests -O tests/Test_Full.csv
          bash ErrLog.sh -P tests -O tests/Test_744.csv -J 744
          bash ErrLog.sh -P tests -O tests/Test_Array4.csv -J '\[4'
          
      # Commit/push/update
